apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ddiaz
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/ddiaz-harbor-project/db@sha256:05378366c89a7e1028d63bf432dd472a97dfdcbcbde6755cd9942690f9d7fe95
        ports: 
        - containerPort: 5432
